//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_P1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelGeneral : DbContext
    {
        public ModelGeneral()
            : base("name=ModelGeneral")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTOR> AUTORs { get; set; }
        public virtual DbSet<CARTE> CARTEs { get; set; }
        public virtual DbSet<CITITOR> CITITORs { get; set; }
        public virtual DbSet<GEN> GENs { get; set; }
        public virtual DbSet<IMPRUMUT> IMPRUMUTs { get; set; }
        public virtual DbSet<REVIEW> REVIEWs { get; set; }
    }
}
